version = 0.1
[default.deploy.parameters]
stack_name = "coralogx-ship"
resolve_s3 = true
s3_prefix = "coralogx-ship"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CoralogixRegion=\"EU1\" CustomDomain=\"\" ApplicationName=\"test1\" SubsystemName=\"test3\" NewlinePattern=\"\" AddMetadata=\"\" CustomMetadata=\"tito=12322\" BlockingPattern=\"\" SamplingRate=\"1\" LogLevel=\"WARN\" S3BucketName=\"myflowlogs-test\" CSVDelimiter=\",\" S3KeyPrefix=\"\" S3KeySuffix=\"\" FunctionMemorySize=\"1024\" FunctionTimeout=\"300\" SNSTopicArn=\"\" SQSTopicArn=\"\" SQSIntegrationTopicArn=\"\" SNSIntegrationTopicArn=\"\" KinesisStreamArn=\"\" IntegrationType=\"S3\" CloudWatchLogGroupName=\"\" LambdaLogRetention=\"5\" NotificationEmail=\"\" StoreAPIKeyInSecretsManager=\"true\" LambdaSubnetID=\"\" LambdaSecurityGroupID=\"\" UsePrivateLink=\"false\" MSKClusterArn=\"\" KafkaTopic=\"\" KafkaBatchSize=\"100\" KafkaBrokers=\"\" KafkaSubnets=\"\" KafkaSecurityGroups=\"\""
image_repositories = []
