version = 0.1
[default.deploy.parameters]
stack_name = "kmsfklfdmds"
resolve_s3 = true
s3_prefix = "kmsfklfdmds"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CoralogixRegion=\"EU1\" CustomDomain=\"\" ApplicationName=\"s3sqs\" SubsystemName=\"s3sqs\" NewlinePattern=\"\" BlockingPattern=\"\" SamplingRate=\"1\" LogLevel=\"WARN\" S3BucketName=\"testwithguy\" CSVDelimiter=\",\" S3KeyPrefix=\"\" S3KeySuffix=\"\" FunctionMemorySize=\"1024\" FunctionTimeout=\"300\" SNSTopicArn=\"arn:aws:sns:us-east-1:771039649440:MySNS\" SQSTopicArn=\" \" SQSIntegrationTopicArn=\"\" SNSIntegrationTopicArn=\"\" IntegrationType=\"S3\" CloudWatchLogGroupName=\"\" LambdaLogRetention=\"5\" NotificationEmail=\"\" StoreAPIKeyInSecretsManager=\"true\" LambdaSubnetID=\"\" LambdaSecurityGroupID=\"\" UsePrivateLink=\"false\""
image_repositories = []
