name: coralogix-aws-shipper tests
on:
  pull_request: 
    branches:
      - master
      - dev
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "template.yaml"
      - "requirements.txt"
      - "Makefile"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        run: |
          pip install cfn-lint
          
        # validate the template file 
      - name: Run cfn-lint
        run: |
          cfn-lint --template template.yaml --region us-east-1 --ignore-checks W 
          
      # - uses: dtolnay/rust-toolchain@stable
      #   with:
      #     toolchain: 1.81.0
      #     components: rustfmt, clippy
      - name: start ssh agent for rust private dependencies
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: run tests
        run: |
          cargo test --all -- --nocapture
