name: url Validation
# the action will get all of the .md files and make sure that all of the link are working 
on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]
    paths:
      - "*.md"
jobs:
  check-docs:
    runs-on: ubuntu-latest
    name: Check Documentation formatting and links
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        npm install -g markdown-link-check
    
    - name: Check documentation formatting and links
      run: |
        find . -regex ".*\.md" | xargs markdown-link-check
